<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="12" total="16" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="18051" started-at="2021-09-16T04:10:28Z" finished-at="2021-09-16T04:10:46Z">
    <groups>
      <group name="sanity">
        <method signature="TestNg5.ValidateAlerts()[pri:4, instance:com.testNg.TestNg5@64bf3bbf]" name="ValidateAlerts" class="com.testNg.TestNg5"/>
        <method signature="TestNg5.ValidateEnterGMOOnline()[pri:1, instance:com.testNg.TestNg5@64bf3bbf]" name="ValidateEnterGMOOnline" class="com.testNg.TestNg5"/>
        <method signature="TestNg5.ValidateGmoOnlineLoadedSuccessfully()[pri:0, instance:com.testNg.TestNg5@64bf3bbf]" name="ValidateGmoOnlineLoadedSuccessfully" class="com.testNg.TestNg5"/>
        <method signature="TestNg5.ValidateOrderQty()[pri:2, instance:com.testNg.TestNg5@64bf3bbf]" name="ValidateOrderQty" class="com.testNg.TestNg5"/>
      </group> <!-- sanity -->
    </groups>
    <test name="Test3" duration-ms="18051" started-at="2021-09-16T04:10:28Z" finished-at="2021-09-16T04:10:46Z">
      <class name="com.testNg.TestNg5">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.testNg.TestNg5@64bf3bbf]" name="beforeSuite" is-config="true" duration-ms="30" started-at="2021-09-16T04:10:28Z" finished-at="2021-09-16T04:10:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.testNg.TestNg5@64bf3bbf]" name="beforeTest" is-config="true" duration-ms="6281" started-at="2021-09-16T04:10:28Z" finished-at="2021-09-16T04:10:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.testNg.TestNg5@64bf3bbf]" name="beforeClass" is-config="true" duration-ms="244" started-at="2021-09-16T04:10:34Z" finished-at="2021-09-16T04:10:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="ValidateGmoOnlineLoadedSuccessfully()[pri:0, instance:com.testNg.TestNg5@64bf3bbf]" name="ValidateGmoOnlineLoadedSuccessfully" duration-ms="68" started-at="2021-09-16T04:10:34Z" finished-at="2021-09-16T04:10:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [OnLine Catalog] but found [Welcome to Green Mountain Outpost]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [OnLine Catalog] but found [Welcome to Green Mountain Outpost]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testNg.TestNg5.ValidateGmoOnlineLoadedSuccessfully(TestNg5.java:76)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateGmoOnlineLoadedSuccessfully -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.testNg.TestNg5@64bf3bbf]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2021-09-16T04:10:34Z" finished-at="2021-09-16T04:10:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="ValidateEnterGMOOnline()[pri:1, instance:com.testNg.TestNg5@64bf3bbf]" name="ValidateEnterGMOOnline" duration-ms="647" started-at="2021-09-16T04:10:34Z" finished-at="2021-09-16T04:10:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateEnterGMOOnline -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.testNg.TestNg5@64bf3bbf]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2021-09-16T04:10:34Z" finished-at="2021-09-16T04:10:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.testNg.TestNg5@64bf3bbf]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2021-09-16T04:10:35Z" finished-at="2021-09-16T04:10:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="ValidateOrderQty()[pri:2, instance:com.testNg.TestNg5@64bf3bbf]" name="ValidateOrderQty" duration-ms="854" started-at="2021-09-16T04:10:35Z" finished-at="2021-09-16T04:10:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateOrderQty -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.testNg.TestNg5@64bf3bbf]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2021-09-16T04:10:36Z" finished-at="2021-09-16T04:10:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="ValidateAlerts()[pri:4, instance:com.testNg.TestNg5@64bf3bbf]" name="ValidateAlerts" duration-ms="9912" started-at="2021-09-16T04:10:36Z" finished-at="2021-09-16T04:10:46Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [You selected OK] but found [You selected Cancel]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [You selected OK] but found [You selected Cancel]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.testNg.TestNg5.ValidateAlerts(TestNg5.java:182)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateAlerts -->
      </class> <!-- com.testNg.TestNg5 -->
    </test> <!-- Test3 -->
  </suite> <!-- Suite -->
</testng-results>
