<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="20325" started-at="2021-08-23T04:27:49Z" finished-at="2021-08-23T04:28:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="20325" started-at="2021-08-23T04:27:49Z" finished-at="2021-08-23T04:28:10Z">
      <class name="com.testNg.TestNg4">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.testNg.TestNg4@4667ae56]" name="beforeSuite" is-config="true" duration-ms="23" started-at="2021-08-23T04:27:49Z" finished-at="2021-08-23T04:27:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.testNg.TestNg4@4667ae56]" name="beforeTest" is-config="true" duration-ms="10714" started-at="2021-08-23T04:27:49Z" finished-at="2021-08-23T04:28:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.testNg.TestNg4@4667ae56]" name="beforeClass" is-config="true" duration-ms="1" started-at="2021-08-23T04:28:00Z" finished-at="2021-08-23T04:28:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.testNg.TestNg4@4667ae56]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2021-08-23T04:28:00Z" finished-at="2021-08-23T04:28:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="ValidateEnterGMOOnline()[pri:1, instance:com.testNg.TestNg4@4667ae56]" name="ValidateEnterGMOOnline" duration-ms="767" started-at="2021-08-23T04:28:00Z" finished-at="2021-08-23T04:28:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateEnterGMOOnline -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.testNg.TestNg4@4667ae56]" name="afterMethod" is-config="true" duration-ms="0" started-at="2021-08-23T04:28:01Z" finished-at="2021-08-23T04:28:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.testNg.TestNg4@4667ae56]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2021-08-23T04:28:01Z" finished-at="2021-08-23T04:28:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="ValidateGmoOnlineLoadedSuccessfully()[pri:1, instance:com.testNg.TestNg4@4667ae56]" name="ValidateGmoOnlineLoadedSuccessfully" duration-ms="22" started-at="2021-08-23T04:28:01Z" finished-at="2021-08-23T04:28:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateGmoOnlineLoadedSuccessfully -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.testNg.TestNg4@4667ae56]" name="afterMethod" is-config="true" duration-ms="0" started-at="2021-08-23T04:28:01Z" finished-at="2021-08-23T04:28:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.testNg.TestNg4@4667ae56]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2021-08-23T04:28:01Z" finished-at="2021-08-23T04:28:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="ValidateOrderQty()[pri:2, instance:com.testNg.TestNg4@4667ae56]" name="ValidateOrderQty" duration-ms="941" started-at="2021-08-23T04:28:01Z" finished-at="2021-08-23T04:28:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateOrderQty -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.testNg.TestNg4@4667ae56]" name="afterMethod" is-config="true" duration-ms="1" started-at="2021-08-23T04:28:02Z" finished-at="2021-08-23T04:28:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.testNg.TestNg4@4667ae56]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2021-08-23T04:28:02Z" finished-at="2021-08-23T04:28:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="ValidateTotalPriceCalculation()[pri:3, instance:com.testNg.TestNg4@4667ae56]" name="ValidateTotalPriceCalculation" duration-ms="243" started-at="2021-08-23T04:28:02Z" finished-at="2021-08-23T04:28:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [719.80] but found [719.8]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [719.80] but found [719.8]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.testNg.TestNg4.ValidateTotalPriceCalculation(TestNg4.java:109)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateTotalPriceCalculation -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.testNg.TestNg4@4667ae56]" name="afterMethod" is-config="true" duration-ms="1" started-at="2021-08-23T04:28:02Z" finished-at="2021-08-23T04:28:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.testNg.TestNg4@4667ae56]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2021-08-23T04:28:02Z" finished-at="2021-08-23T04:28:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="ValidateAlerts()[pri:4, instance:com.testNg.TestNg4@4667ae56]" name="ValidateAlerts" duration-ms="7543" started-at="2021-08-23T04:28:02Z" finished-at="2021-08-23T04:28:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [You selected OK] but found [You selected Cancel]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [You selected OK] but found [You selected Cancel]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.testNg.TestNg4.ValidateAlerts(TestNg4.java:145)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateAlerts -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.testNg.TestNg4@4667ae56]" name="afterClass" is-config="true" duration-ms="1" started-at="2021-08-23T04:28:10Z" finished-at="2021-08-23T04:28:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.testNg.TestNg4@4667ae56]" name="afterMethod" is-config="true" duration-ms="0" started-at="2021-08-23T04:28:10Z" finished-at="2021-08-23T04:28:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.testNg.TestNg4@4667ae56]" name="afterTest" is-config="true" duration-ms="0" started-at="2021-08-23T04:28:10Z" finished-at="2021-08-23T04:28:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.testNg.TestNg4@4667ae56]" name="afterSuite" is-config="true" duration-ms="1" started-at="2021-08-23T04:28:10Z" finished-at="2021-08-23T04:28:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.testNg.TestNg4 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
